In [32]:
from keras.layers import Dense
import tensorflow as tf
import numpy as np

In [33]:
x = np.arange(-10,10, .01)
y = 3*x**3 + 7*x**2 - 12*x + 2

In [34]:
model = tf.keras.Sequential([
        Dense(units=32, input_shape=(1,), activation='relu'),
        Dense(units=128, activation='relu'),
        Dense(units=256, activation='relu'),
        Dense(units=256, activation='relu'),
        Dense(units=512, activation='relu'),
        # Dense(units=1, activation='tanh')
        Dense(units=1)
    ]
)

Epoch 1/100
63/63 [==============================] - 1s 3ms/step - loss: 706152.6875
Epoch 2/100
63/63 [==============================] - 0s 3ms/step - loss: 219659.6250
Epoch 3/100
63/63 [==============================] - 0s 3ms/step - loss: 202806.7031
Epoch 4/100
63/63 [==============================] - 0s 3ms/step - loss: 166874.3125
Epoch 5/100
63/63 [==============================] - 0s 3ms/step - loss: 115759.4531
Epoch 6/100
63/63 [==============================] - 0s 3ms/step - loss: 49050.3633
Epoch 7/100
63/63 [==============================] - 0s 3ms/step - loss: 17053.2891
Epoch 8/100
63/63 [==============================] - 0s 3ms/step - loss: 7346.2373
Epoch 9/100
63/63 [==============================] - 0s 3ms/step - loss: 4129.0107
Epoch 10/100
63/63 [==============================] - 0s 3ms/step - loss: 2666.4399
Epoch 11/100
63/63 [==============================] - 0s 3ms/step - loss: 2643.7029
Epoch 12/100
63/63 [==============================] - 0s 3ms/step - loss:

In [35]:
y

array([-2178.      , -2170.528297, -2163.073176, ...,  3551.247219,
        3561.478776,  3571.729697])

In [41]:
model.predict(np.array([-3,-2,-1,0,1,2,3]))

1/1 [==============================] - 0s 16ms/step


array([[ 18.665812 ],
       [ 28.836863 ],
       [ 15.883552 ],
       [  1.2794216],
       [ -1.2705929],
       [ 27.903185 ],
       [107.78393  ]], dtype=float32)

In [43]:
a = np.array([-3,-2,-1,0,1,2,3])
b = 3*a**3 + 7*a**2 - 12*a + 2

In [44]:
b

array([ 20,  30,  18,   2,   0,  30, 110])

In [45]:
model.predict(a)

1/1 [==============================] - 0s 17ms/step


array([[ 18.665812 ],
       [ 28.836863 ],
       [ 15.883552 ],
       [  1.2794216],
       [ -1.2705929],
       [ 27.903185 ],
       [107.78393  ]], dtype=float32)

In [48]:
out = model.predict(a)

1/1 [==============================] - 0s 61ms/step


In [70]:
from pprint import pprint
i = 0
for idx in range(-3,4):
  print("x = {}, y = {res:.2f}".format(idx, res=out[i][0]))
  i += 1

x = -3, y = 18.67
x = -2, y = 28.84
x = -1, y = 15.88
x = 0, y = 1.28
x = 1, y = -1.27
x = 2, y = 27.90
x = 3, y = 107.78
